// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int smallerThanOrEqualToPoint5 = 0;
		int greaterThanPoint5 = 0;
		for (int i = 0; i < n; i++) {
			if (Math.random() <= 0.5) {
				smallerThanOrEqualToPoint5++;
			}
			else {
				greaterThanPoint5++;
			}
		}

		System.out.println("> 0.5: " + greaterThanPoint5 + " times");
		System.out.println("<= 0.5: " + smallerThanOrEqualToPoint5 + " times");
		if (greaterThanPoint5 > 0 && smallerThanOrEqualToPoint5 > 0) {
			System.out.println("Ratio: " + (double)greaterThanPoint5 / smallerThanOrEqualToPoint5);
		}
	}
}
